"""your message

Revision ID: 9718f016dbf0
Revises: f62bb60adb26
Create Date: 2024-06-30 14:01:44.449569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9718f016dbf0'
down_revision = 'f62bb60adb26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
